// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFetchHistory(arg1) {
  return window['go']['main']['App']['AddFetchHistory'](arg1);
}

export function AddToDownloadQueue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddToDownloadQueue'](arg1, arg2, arg3, arg4);
}

export function CancelAllQueuedItems() {
  return window['go']['main']['App']['CancelAllQueuedItems']();
}

export function CheckAPIStatus(arg1, arg2) {
  return window['go']['main']['App']['CheckAPIStatus'](arg1, arg2);
}

export function CheckAtmosSupport(arg1) {
  return window['go']['main']['App']['CheckAtmosSupport'](arg1);
}

export function CheckFFmpegInstalled() {
  return window['go']['main']['App']['CheckFFmpegInstalled']();
}

export function CheckFilesExistence(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckFilesExistence'](arg1, arg2, arg3);
}

export function CheckTrackAvailability(arg1) {
  return window['go']['main']['App']['CheckTrackAvailability'](arg1);
}

export function ClearAllDownloads() {
  return window['go']['main']['App']['ClearAllDownloads']();
}

export function ClearCompletedDownloads() {
  return window['go']['main']['App']['ClearCompletedDownloads']();
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function ClearFetchHistory() {
  return window['go']['main']['App']['ClearFetchHistory']();
}

export function ClearFetchHistoryByType(arg1) {
  return window['go']['main']['App']['ClearFetchHistoryByType'](arg1);
}

export function ConvertAudio(arg1) {
  return window['go']['main']['App']['ConvertAudio'](arg1);
}

export function CreateM3U8File(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateM3U8File'](arg1, arg2, arg3);
}

export function DecodeAudioForAnalysis(arg1) {
  return window['go']['main']['App']['DecodeAudioForAnalysis'](arg1);
}

export function DeleteDownloadHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteDownloadHistoryItem'](arg1);
}

export function DeleteFetchHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteFetchHistoryItem'](arg1);
}

export function DownloadAvatar(arg1) {
  return window['go']['main']['App']['DownloadAvatar'](arg1);
}

export function DownloadCover(arg1) {
  return window['go']['main']['App']['DownloadCover'](arg1);
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function DownloadGalleryImage(arg1) {
  return window['go']['main']['App']['DownloadGalleryImage'](arg1);
}

export function DownloadHeader(arg1) {
  return window['go']['main']['App']['DownloadHeader'](arg1);
}

export function DownloadLyrics(arg1) {
  return window['go']['main']['App']['DownloadLyrics'](arg1);
}

export function DownloadTrack(arg1) {
  return window['go']['main']['App']['DownloadTrack'](arg1);
}

export function ExportFailedDownloads() {
  return window['go']['main']['App']['ExportFailedDownloads']();
}

export function GetBrewPath() {
  return window['go']['main']['App']['GetBrewPath']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetDownloadProgress() {
  return window['go']['main']['App']['GetDownloadProgress']();
}

export function GetDownloadQueue() {
  return window['go']['main']['App']['GetDownloadQueue']();
}

export function GetFetchHistory() {
  return window['go']['main']['App']['GetFetchHistory']();
}

export function GetFileSizes(arg1) {
  return window['go']['main']['App']['GetFileSizes'](arg1);
}

export function GetFlacInfoBatch(arg1) {
  return window['go']['main']['App']['GetFlacInfoBatch'](arg1);
}

export function GetPreviewURL(arg1) {
  return window['go']['main']['App']['GetPreviewURL'](arg1);
}

export function GetSpotifyMetadata(arg1) {
  return window['go']['main']['App']['GetSpotifyMetadata'](arg1);
}

export function GetStreamingURLs(arg1, arg2) {
  return window['go']['main']['App']['GetStreamingURLs'](arg1, arg2);
}

export function InstallFFmpegWithBrew() {
  return window['go']['main']['App']['InstallFFmpegWithBrew']();
}

export function IsBrewFFmpegInstalled() {
  return window['go']['main']['App']['IsBrewFFmpegInstalled']();
}

export function IsFFmpegInstalled() {
  return window['go']['main']['App']['IsFFmpegInstalled']();
}

export function IsFFprobeInstalled() {
  return window['go']['main']['App']['IsFFprobeInstalled']();
}

export function ListAudioFilesInDir(arg1) {
  return window['go']['main']['App']['ListAudioFilesInDir'](arg1);
}

export function ListDirectoryFiles(arg1) {
  return window['go']['main']['App']['ListDirectoryFiles'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function MarkDownloadItemFailed(arg1, arg2) {
  return window['go']['main']['App']['MarkDownloadItemFailed'](arg1, arg2);
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PreviewRenameFiles(arg1, arg2) {
  return window['go']['main']['App']['PreviewRenameFiles'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadFileAsBase64(arg1) {
  return window['go']['main']['App']['ReadFileAsBase64'](arg1);
}

export function ReadFileMetadata(arg1) {
  return window['go']['main']['App']['ReadFileMetadata'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['main']['App']['ReadImageAsBase64'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RenameFileTo(arg1, arg2) {
  return window['go']['main']['App']['RenameFileTo'](arg1, arg2);
}

export function RenameFilesByMetadata(arg1, arg2) {
  return window['go']['main']['App']['RenameFilesByMetadata'](arg1, arg2);
}

export function ResampleAudio(arg1) {
  return window['go']['main']['App']['ResampleAudio'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSpectrumImage(arg1, arg2) {
  return window['go']['main']['App']['SaveSpectrumImage'](arg1, arg2);
}

export function SearchSpotify(arg1) {
  return window['go']['main']['App']['SearchSpotify'](arg1);
}

export function SearchSpotifyByType(arg1) {
  return window['go']['main']['App']['SearchSpotifyByType'](arg1);
}

export function SelectAudioFiles() {
  return window['go']['main']['App']['SelectAudioFiles']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SelectImageVideo() {
  return window['go']['main']['App']['SelectImageVideo']();
}

export function SkipDownloadItem(arg1, arg2) {
  return window['go']['main']['App']['SkipDownloadItem'](arg1, arg2);
}
