// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function AddFetchHistory(arg1:backend.FetchHistoryItem):Promise<void>;

export function AddToDownloadQueue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CancelAllQueuedItems():Promise<void>;

export function CheckAPIStatus(arg1:string,arg2:string):Promise<boolean>;

export function CheckAtmosSupport(arg1:string):Promise<string>;

export function CheckFFmpegInstalled():Promise<boolean>;

export function CheckFilesExistence(arg1:string,arg2:string,arg3:Array<main.CheckFileExistenceRequest>):Promise<Array<main.CheckFileExistenceResult>>;

export function CheckTrackAvailability(arg1:string):Promise<string>;

export function ClearAllDownloads():Promise<void>;

export function ClearCompletedDownloads():Promise<void>;

export function ClearDownloadHistory():Promise<void>;

export function ClearFetchHistory():Promise<void>;

export function ClearFetchHistoryByType(arg1:string):Promise<void>;

export function ConvertAudio(arg1:main.ConvertAudioRequest):Promise<Array<backend.ConvertAudioResult>>;

export function CreateM3U8File(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function DecodeAudioForAnalysis(arg1:string):Promise<backend.AnalysisDecodeResponse>;

export function DeleteDownloadHistoryItem(arg1:string):Promise<void>;

export function DeleteFetchHistoryItem(arg1:string):Promise<void>;

export function DownloadAvatar(arg1:main.AvatarDownloadRequest):Promise<backend.AvatarDownloadResponse>;

export function DownloadCover(arg1:main.CoverDownloadRequest):Promise<backend.CoverDownloadResponse>;

export function DownloadFFmpeg():Promise<main.DownloadFFmpegResponse>;

export function DownloadGalleryImage(arg1:main.GalleryImageDownloadRequest):Promise<backend.GalleryImageDownloadResponse>;

export function DownloadHeader(arg1:main.HeaderDownloadRequest):Promise<backend.HeaderDownloadResponse>;

export function DownloadLyrics(arg1:main.LyricsDownloadRequest):Promise<backend.LyricsDownloadResponse>;

export function DownloadTrack(arg1:main.DownloadRequest):Promise<main.DownloadResponse>;

export function ExportFailedDownloads():Promise<string>;

export function GetBrewPath():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetDefaults():Promise<Record<string, string>>;

export function GetDownloadHistory():Promise<Array<backend.HistoryItem>>;

export function GetDownloadProgress():Promise<backend.ProgressInfo>;

export function GetDownloadQueue():Promise<backend.DownloadQueueInfo>;

export function GetFetchHistory():Promise<Array<backend.FetchHistoryItem>>;

export function GetFileSizes(arg1:Array<string>):Promise<Record<string, number>>;

export function GetFlacInfoBatch(arg1:Array<string>):Promise<Array<backend.FlacInfo>>;

export function GetPreviewURL(arg1:string):Promise<string>;

export function GetSpotifyMetadata(arg1:main.SpotifyMetadataRequest):Promise<string>;

export function GetStreamingURLs(arg1:string,arg2:string):Promise<string>;

export function InstallFFmpegWithBrew():Promise<main.InstallFFmpegWithBrewResponse>;

export function IsBrewFFmpegInstalled():Promise<boolean>;

export function IsFFmpegInstalled():Promise<boolean>;

export function IsFFprobeInstalled():Promise<boolean>;

export function ListAudioFilesInDir(arg1:string):Promise<Array<backend.FileInfo>>;

export function ListDirectoryFiles(arg1:string):Promise<Array<backend.FileInfo>>;

export function LoadSettings():Promise<Record<string, any>>;

export function MarkDownloadItemFailed(arg1:string,arg2:string):Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PreviewRenameFiles(arg1:Array<string>,arg2:string):Promise<Array<backend.RenamePreview>>;

export function Quit():Promise<void>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function ReadFileMetadata(arg1:string):Promise<backend.AudioMetadata>;

export function ReadImageAsBase64(arg1:string):Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RenameFileTo(arg1:string,arg2:string):Promise<void>;

export function RenameFilesByMetadata(arg1:Array<string>,arg2:string):Promise<Array<backend.RenameResult>>;

export function ResampleAudio(arg1:main.ResampleAudioRequest):Promise<Array<backend.ResampleResult>>;

export function SaveSettings(arg1:Record<string, any>):Promise<void>;

export function SaveSpectrumImage(arg1:string,arg2:string):Promise<string>;

export function SearchSpotify(arg1:main.SpotifySearchRequest):Promise<backend.SearchResponse>;

export function SearchSpotifyByType(arg1:main.SpotifySearchByTypeRequest):Promise<Array<backend.SearchResult>>;

export function SelectAudioFiles():Promise<Array<string>>;

export function SelectFile():Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;

export function SelectImageVideo():Promise<Array<string>>;

export function SkipDownloadItem(arg1:string,arg2:string):Promise<void>;
